export type Chemistry = 'Viologen' | 'Prussian blue';
export type Region = { x:number; y:number; w:number; h:number };
export type DeviceMeasurement = { voltage:number; current:number; charge:number; cycles:number };
export type Reading = { id:string; sessionId:string; stripId:string; deviceId:string; chemistry:Chemistry; start:string; end:string; created:string; calibration:string; version:string; exposure:number|null; intensity:number; color:string; uncertainty:number|null; saturated:boolean; quality:string[]; image:string; original:string; region:Region; location:string; notes:string; demo:true; device?:DeviceMeasurement };
export type AnalysisInput = Omit<Reading,'id'|'created'|'version'|'exposure'|'intensity'|'color'|'uncertainty'|'saturated'|'quality'|'demo'> & { scenario:string };
export interface AuthenticationAPI { login(email:string,password:string):Promise<void>; createAccount(email:string,password:string):Promise<void>; resetPassword(email:string):Promise<void>; signOut():Promise<void> }
export interface AnalysisAPI { analyse(input:AnalysisInput):Promise<Reading> }
export interface RecordsAPI { list():Promise<Reading[]>; save(record:Reading):Promise<void>; delete(id:string):Promise<void>; reset():Promise<void> }
export interface DeviceAPI { getMeasurements(deviceId:string):Promise<DeviceMeasurement|null> }
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const unavailable=async()=>{await pause(650);throw new Error('Account services are not connected in this prototype. Use Explore demo to try Chromatrack.');};
export const authenticationAPI:AuthenticationAPI={login:unavailable,createAccount:unavailable,resetPassword:unavailable,signOut:async()=>{}};
export const deviceAPI:DeviceAPI={getMeasurements:async()=>null};
export const analysisAPI:AnalysisAPI={async analyse(input){await pause(1450);if(input.scenario==='error')throw new Error('Simulated service error. Your photo is still here. Choose another demo scenario or try again.');const compatible=input.calibration===(input.chemistry==='Viologen'?'vio-v1':'pb-v1');const saturated=input.scenario==='saturated';return {...input,id:crypto.randomUUID(),created:new Date().toISOString(),version:compatible?'1.2.0':'Not available',exposure:compatible&&!saturated?2.48:null,intensity:saturated?98:62,color:input.chemistry==='Viologen'?'#8261B5':'#356C98',uncertainty:compatible&&!saturated?0.31:null,saturated,quality:input.scenario==='quality'?['Blur detected — retake with a steady camera.','Glare detected — avoid direct reflections.','Uneven lighting — use diffuse light.']:['Blur: low (simulated)','Glare: low (simulated)','Lighting: even (simulated)'],demo:true};}};
export const SAMPLE='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="520" viewBox="0 0 900 520"><rect width="900" height="520" fill="#eaecea"/><rect x="80" y="160" width="740" height="200" rx="14" fill="#fff"/><rect x="115" y="193" width="455" height="134" rx="3" fill="#8261b5"/><rect x="615" y="199" width="44" height="120" fill="#f8f8f8" stroke="#ddd"/><rect x="672" y="199" width="44" height="120" fill="#999"/><rect x="729" y="199" width="44" height="120" fill="#282b33"/><text x="450" y="432" text-anchor="middle" font-family="sans-serif" font-size="22" fill="#657176">ILLUSTRATIVE DEMO STRIP · NOT A MEASUREMENT</text></svg>`);
export function seedRecords():Reading[]{const out:Reading[]=[];[0,1,3,5,8,12].forEach((day,i)=>{const end=new Date();end.setDate(end.getDate()-day);end.setHours(16,30,0,0);const start=new Date(end);start.setHours(8,30,0,0);const base:Reading={id:`seed-${i}`,sessionId:`session-${i}`,stripId:`CT-${String(2408-i).padStart(4,'0')}`,deviceId:'',chemistry:i===4?'Prussian blue':'Viologen',start:start.toISOString(),end:end.toISOString(),created:end.toISOString(),calibration:i===3?'none':i===4?'pb-v1':'vio-v1',version:i===3?'Not available':'1.2.0',exposure:i===3?null:[2.48,1.92,3.12,0,1.64,2.24][i],intensity:[62,48,78,35,41,56][i],color:i===4?'#356C98':'#8261B5',uncertainty:i===3?null:0.31,saturated:false,quality:['Blur: low (simulated)','Glare: low (simulated)','Lighting: even (simulated)'],image:SAMPLE,original:SAMPLE,region:{x:12.7,y:37.1,w:50.6,h:25.8},location:'Materials laboratory',notes:'Example session. All measurements are synthetic.',demo:true};out.push(base);if(i===0){[2,4,6].forEach((hour,j)=>{const t=new Date(start.getTime()+hour*3600000);out.push({...base,id:`seed-0-${j}`,end:t.toISOString(),created:t.toISOString(),exposure:[0.56,1.16,1.84][j],intensity:[14,29,46][j]});});}});return out;}
async function db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open('chromatrack-demo',1);r.onupgradeneeded=()=>r.result.createObjectStore('records',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('Browser storage is unavailable. Please allow local storage.'));});}
async function operation<T>(mode:IDBTransactionMode,run:(s:IDBObjectStore)=>IDBRequest):Promise<T>{const d=await db();return new Promise((res,rej)=>{const t=d.transaction('records',mode);const r=run(t.objectStore('records'));t.oncomplete=()=>{d.close();res(r.result as T);};t.onerror=()=>{d.close();rej(new Error('Could not save locally. Browser storage may be full. Export or delete older records and retry.'));};});}
export const recordsAPI:RecordsAPI={list:()=>operation('readonly',s=>s.getAll()),save:r=>operation('readwrite',s=>s.put(r)),delete:id=>operation('readwrite',s=>s.delete(id)),reset:()=>operation('readwrite',s=>s.clear())};
export function duration(r:Pick<Reading,'start'|'end'>){return (new Date(r.end).getTime()-new Date(r.start).getTime())/3600000;}
export function finalSessions(records:Reading[]){const map=new Map<string,Reading>();records.forEach(r=>{const key=r.sessionId+'|'+r.calibration;const old=map.get(key);if(!old||new Date(r.end)>new Date(old.end))map.set(key,r);});return [...map.values()].sort((a,b)=>Date.parse(b.end)-Date.parse(a.end));}
